export type FieldVerification =
  | "verified-production-dashboard"
  | "verified-live-org"
  | "verified-derived"
  | "derived-unverified"
  | "optional-probed";
export interface FieldMapping {
  apiName: string;
  verified: boolean;
  verification: FieldVerification;
}
const verified = (apiName: string): FieldMapping => ({
  apiName,
  verified: true,
  verification: "verified-production-dashboard",
});

export const PUBLIC_EXCLUDED_SUBMARKETS = [
  "Chicago North",
  "I-39 Corridor",
  "McHenry County",
  "Other IL",
  "Other IN",
  "Other WI",
  "Rockford",
] as const;
const excluded = new Set(
  PUBLIC_EXCLUDED_SUBMARKETS.map((name) => name.trim().toLocaleLowerCase()),
);
export const isPublicExcludedSubmarket = (name: string) =>
  excluded.has(name.trim().toLocaleLowerCase());
export const ELIGIBLE_MARKET_UNIVERSE_SCOPE =
  "Eligible 20K+ Market Universe" as const;

export const verifiedDerivedMetrics = {
  speculativeShare: {
    verification: "verified-derived" as const,
    formula: "Under_Construction_Available_SF__c / Under_Construction_SF__c",
    validatedAgainst: "live Chicago 2026 Q2 report contract",
  },
};

export {
  CHICAGO_INDUSTRIAL_REPORT_SUBMARKETS,
  canonicalChicagoSubmarket,
} from "../../../src/report-engine/submarkets.ts";

export const salesforceFieldMap = {
  marketData: {
    object: verified("Market_Data__c"),
    id: verified("Id"),
    name: verified("Name"),
    market: verified("Market__c"),
    marketCode: verified("Market_Code__c"),
    submarket: verified("Submarket__c"),
    submarketCode: verified("Submarket_Code__c"),
    state: verified("State__c"),
    periodStart: verified("Period_Start__c"),
    periodEnd: verified("Period_End__c"),
    periodType: verified("Period_Type__c"),
    quarter: verified("Quarter__c"),
    period: verified("Quarter_Label__c"),
    year: verified("Year__c"),
    externalId: verified("External_Id__c"),
    asOf: verified("As_Of__c"),
    lastCalculatedAt: verified("Last_Calculated_Timestamp__c"),
    calcVersion: verified("Calc_Version__c"),
    calcNotes: verified("Calc_Notes__c"),
    dataSource: verified("Data_Source__c"),
    dataSourceMethod: verified("Data_Source_Method__c"),
    inventorySf: verified("Inventory_SF__c"),
    inventoryBuildings: verified("Inventory_Buildings__c"),
    deliveredSf: verified("Delivered_SF__c"),
    deliveredBuildings: verified("Delivered_Buildings__c"),
    deliveredPercent: verified("Delivered_Percent_of_Inventory__c"),
    underConstructionSf: verified("Under_Construction_SF__c"),
    underConstructionBuildings: verified("Under_Construction_Buildings__c"),
    underConstructionAvailableSf: verified(
      "Under_Construction_Available_SF__c",
    ),
    underConstructionPercent: verified(
      "Under_Construction_Percent_of_Inventory__c",
    ),
    quarterlyNetAbsorptionSf: verified("Total_Net_Absorption_SF__c"),
    directNetAbsorptionSf: verified("Direct_Net_Absorption_SF__c"),
    subletNetAbsorptionSf: verified("Sublet_Net_Absorption_SF__c"),
    totalGrossAbsorptionSf: verified("Total_Gross_Absorption_SF__c"),
    directGrossAbsorptionSf: verified("Direct_Gross_Absorption_SF__c"),
    subletGrossAbsorptionSf: verified("Sublet_Gross_Absorption_SF__c"),
    netAbsorptionNewSupplySf: verified("Net_Absorption_of_New_Supply_SF__c"),
    vacancyRate: verified("Total_Vacant_Percent__c"),
    totalVacantSf: verified("Total_Vacant_SF__c"),
    directVacantRate: verified("Direct_Vacant_Percent__c"),
    directVacantSf: verified("Direct_Vacant_SF__c"),
    subletVacantRate: verified("Sublet_Vacant_Percent__c"),
    subletVacantSf: verified("Sublet_Vacant_SF__c"),
    availabilityRate: verified("Total_Available_Percent__c"),
    totalAvailableSf: verified("Total_Available_SF__c"),
    directAvailableRate: verified("Direct_Available_Percent__c"),
    directAvailableSf: verified("Direct_Available_SF__c"),
    subletAvailableRate: verified("Sublet_Available_Percent__c"),
    subletAvailableSf: verified("Sublet_Available_SF__c"),
    totalVacantAvailableRate: verified("Total_Vacant_Available_Percent__c"),
    totalVacantAvailableSf: verified("Total_Vacant_Available_SF__c"),
    directVacantAvailableRate: verified("Direct_Vacant_Available_Percent__c"),
    directVacantAvailableSf: verified("Direct_Vacant_Available_SF__c"),
    subletVacantAvailableRate: verified("Sublet_Vacant_Available_Percent__c"),
    subletVacantAvailableSf: verified("Sublet_Vacant_Available_SF__c"),
    leasingActivitySf: verified("Total_Leasing_Activity_SF__c"),
    leasingActivityDeals: verified("Total_Leasing_Activity_Deals__c"),
    directLeasingActivitySf: verified("Direct_Leasing_Activity_SF__c"),
    directLeasingActivityDeals: verified("Direct_Leasing_Activity_Deals__c"),
    subletLeasingActivitySf: verified("Sublet_Leasing_Activity_SF__c"),
    subletLeasingActivityDeals: verified("Sublet_Leasing_Activity_Deals__c"),
    askingNetRentPsf: verified("Overall_Net_Rent_SF__c"),
    overallAllServiceRentPsf: verified("Overall_All_Service_Rent_SF__c"),
    directNetRentPsf: verified("Direct_Net_Rent_SF__c"),
    directAllServiceRentPsf: verified("Direct_All_Service_Rent_SF__c"),
    subletNetRentPsf: verified("Sublet_Net_Rent_SF__c"),
    subletAllServiceRentPsf: verified("Sublet_All_Service_Rent_SF__c"),
    salesVolume: verified("Sales_Volume_USD__c"),
    salesTransactions: verified("Sales_Transactions__c"),
    averageSalesPrice: verified("Average_Sales_Price__c"),
    averageSalesPriceSf: verified("Average_Sales_Price_SF__c"),
    averageSoldSf: verified("Average_Sold_SF__c"),
    medianSalesPrice: verified("Median_Sales_Price__c"),
    medianSalesPricePerBuildingSf: verified(
      "Median_Sales_Price_Per_Building_SF__c",
    ),
    medianSoldBuildingSizeSf: verified("Median_Sold_Building_Size_SF__c"),
    totalSoldSf: verified("Total_Sold_SF__c"),
    totalSoldBuildings: verified("Total_Sold_Buildings__c"),
    totalLandAcresSold: verified("Total_Land_Acres_Sold_AC__c"),
    averageActualCapRate: verified("Average_Actual_CAP_Rate__c"),
    medianActualCapRate: verified("Median_Actual_CAP_Rate__c"),
    overallModeledCapRate: verified("Overall_Modeled_CAP_Rate__c"),
    classAModeledCapRate: verified("Class_A_Modeled_CAP_Rate__c"),
    classBModeledCapRate: verified("Class_B_Modeled_CAP_Rate__c"),
    classCModeledCapRate: verified("Class_C_Modeled_CAP_Rate__c"),
    occupancySf: verified("Occupancy_SF__c"),
    occupancyRate: verified("Occupancy_Percent__c"),
  },
  propertyData: {
    object: verified("Property_Data__c"),
    id: verified("Id"),
    name: verified("Name"),
    propertyId: verified("Property__c"),
    availableSf: verified("Available_SF_Total__c"),
    submarket: verified("Submarket__c"),
    quarter: verified("Quarter__c"),
    periodEnd: verified("Period_End__c"),
    scope: verified("Property_Data_Scope__c"),
    marketDataId: verified("Market_Data__c"),
    periodStart: verified("Period_Start__c"),
    inventorySf: verified("Inventory_SF__c"),
    vacantSf: verified("Vacant_SF_Total__c"),
    quarterlyNetAbsorptionSf: verified("Net_Absorption_SF_Total__c"),
    leasingActivitySf: verified("Leasing_Activity_SF_Total__c"),
    deliveredSf: verified("Deliveries_SF__c"),
    underConstructionSf: verified("Under_Construction_SF__c"),
    underConstructionAvailableSf: verified(
      "Under_Construction_Available_SF__c",
    ),
    salesVolume: verified("Sales_Volume_USD__c"),
  },
  property: {
    object: verified("ascendix__Property__c"),
    id: verified("Id"),
    name: verified("Name"),
    street: verified("ascendix__Street__c"),
    city: verified("ascendix__City__c"),
    state: verified("State__c"),
    zip: verified("Zip_Code__c"),
    county: verified("County__c"),
    msa: verified("MSA__c"),
    submarket: verified("Submarket_Picklist__c"),
    propertyType: verified("Property_Type__c"),
    propertyClass: verified("ascendix__PropertyClass__c"),
    propertySubtype: verified("ascendix__PropertySubType__c"),
    developerId: verified("ascendix__Developer__c"),
    developerName: verified("ascendix__Developer__r.Name"),
    ownerId: verified("ascendix__OwnerLandlord__c"),
    ownerName: verified("ascendix__OwnerLandlord__r.Name"),
    image: verified("ascendix__PrimaryImage__c"),
    buildingStatus: verified("ascendix__BuildingStatus__c"),
    constructionStart: verified("Construction_Start_Date__c"),
    constructionCompleted: verified("Construction_Completed_Date__c"),
    latitude: verified("ascendix__Geolocation__Latitude__s"),
    longitude: verified("ascendix__Geolocation__Longitude__s"),
    totalAvailableArea: verified("ascendix__TotalAvailableArea__c"),
    yearBuilt: verified("ascendix__YearBuilt__c"),
    monthBuilt: verified("Month_Built__c"),
    expansionType: verified("ascendix__ExpansionType__c"),
  },
  availability: {
    object: verified("ascendix__Availability__c"),
    propertyId: verified("ascendix__Property__c"),
    sizeSf: verified("ascendix__AvailableArea__c"),
    status: verified("ascendix__Status__c"),
    recordType: verified("RecordType.Name"),
    vacancyType: verified("Vacancy_Type__c"),
    useType: verified("Use_Type__c"),
    useSubtype: verified("ascendix__UseSubType__c"),
    brokerCompany: verified("Listing_Broker_Company__c"),
    broker2Company: verified("Listing_Broker_2_Company__c"),
    broker3Company: verified("Listing_Broker_3_Company__c"),
    brokerContactId: verified("Listing_Broker_Contact__c"),
    brokerContactName: verified("Listing_Broker_Contact__r.Name"),
    broker2ContactId: verified("Listing_Broker_2_Contact__c"),
    broker2ContactName: verified("Listing_Broker_2_Contact__r.Name"),
    broker3ContactId: verified("Listing_Broker_3_Contact__c"),
    broker3ContactName: verified("Listing_Broker_3_Contact__r.Name"),
  },
  lease: {
    object: verified("ascendix__Lease__c"),
    propertyId: verified("ascendix__Property__c"),
    sizeSf: verified("ascendix__Size__c"),
    offMarketDate: verified("Off_Market_Date__c"),
    leeDeal: verified("Lee_Deal__c"),
    type: verified("Deal_Type__c"),
    subtype: verified("Deal_Sub_Type__c"),
    waitingForComp: verified("Waiting_for_Comp__c"),
    useType: verified("Use_Type__c"),
    tenant: verified("ascendix__Tenant__r.Name"),
    leaseRate: verified("ascendix__LeaseRatePerUOM__c"),
    term: verified("Term__c"),
    propertySubtype: verified("Property_Sub_Type__c"),
    isDealConfidential: verified("Is_Deal_Confidential__c"),
  },
  sale: {
    object: verified("ascendix__Sale__c"),
    propertyId: verified("ascendix__Property__c"),
    buildingSf: verified("Building_SF__c"),
    offMarketDate: verified("Off_Market_Date__c"),
    saleDate: verified("ascendix__SaleDate__c"),
    price: verified("ascendix__SalePrice__c"),
    pricePerUom: verified("ascendix__SalePricePerUOM__c"),
    capRate: verified("ascendix__CapRatePercent__c"),
    type: verified("Sale_Type__c"),
    category: verified("Sale_Category__c"),
    seller: verified("ascendix__Seller__r.Name"),
    buyerId: verified("ascendix__Buyer__c"),
    buyer: verified("ascendix__Buyer__r.Name"),
    normalizedBuyer: verified("ascendix__Buyer__r.Normalized_Name__c"),
    leeDeal: verified("Lee_Deal__c"),
    isLeeDeal: verified("Is_Lee_Deal__c"),
    listingBroker: verified("ascendix__ListingBrokerCompany__c"),
    procuringBroker: verified("Procuring_Broker_1_Company__c"),
  },
  contributor: {
    object: verified("Market_Data_Contributor__c"),
    id: verified("Id"),
    name: verified("Name"),
    period: verified("Quarter_Label__c"),
    submarket: verified("Submarket__c"),
    category: verified("Contributor_Category__c"),
    rank: verified("Rank__c"),
    sortValue: verified("Sort_Value__c"),
    metricValue: verified("Metric_Value__c"),
    metricLabel: verified("Metric_Label__c"),
    displayValue: verified("Display_Value__c"),
    displayTitle: verified("Display_Title__c"),
    displaySubtitle: verified("Display_Subtitle__c"),
    sourceObject: verified("Source_Object__c"),
    sourceRecordId: verified("Source_Record_ID__c"),
    sourceRecordName: verified("Source_Record_Name__c"),
    address: verified("Address__c"),
    propertyName: verified("Property_Name__c"),
    propertyType: verified("Property_Type__c"),
    buildingClass: verified("Building_Class__c"),
    buildingStatus: verified("Building_Status__c"),
    buildingSf: verified("Building_SF__c"),
    availableSf: verified("Available_SF__c"),
    deliveredSf: verified("Delivered_SF__c"),
    underConstructionSf: verified("Under_Construction_SF__c"),
    leaseSf: verified("Lease_SF__c"),
    salePrice: verified("Sale_Price__c"),
    tenantName: verified("Tenant_Name__c"),
    buyerName: verified("Buyer_Name__c"),
    dealType: verified("Deal_Type__c"),
    dealSubtype: verified("Deal_Sub_Type__c"),
    sourceStatus: verified("Source_Status__c"),
    vacancyType: verified("Vacancy_Type__c"),
    isLeeAvailability: verified("Is_Lee_Availability__c"),
    isLeeDeal: verified("Is_Lee_Deal__c"),
    included: verified("Included_In_Report__c"),
    active: verified("Active_In_Run__c"),
    propertyId: verified("Property__c"),
    availabilityId: verified("Availability__c"),
    leaseId: verified("Lease__c"),
    saleId: verified("Sale__c"),
    marketDataId: verified("Market_Data__c"),
    marketDataSubmarket: verified("Market_Data__r.Submarket__c"),
    marketDataPeriod: verified("Market_Data__r.Quarter_Label__c"),
  },
} as const;

export const contributorOptionalRelationshipFields = [
  "Property__r.Id",
  "Property__r.ascendix__Street__c",
  "Property__r.ascendix__City__c",
  "Property__r.State__c",
  "Property__r.Zip_Code__c",
  "Property__r.ascendix__PropertySubType__c",
  "Property__r.Property_Type__c",
  "Property__r.ascendix__ExpansionType__c",
  "Property__r.ascendix__Developer__c",
  "Property__r.ascendix__Developer__r.Name",
  "Property__r.ascendix__OwnerLandlord__c",
  "Property__r.ascendix__OwnerLandlord__r.Name",
  "Property__r.ascendix__PrimaryImage__c",
  "Lease__r.ascendix__Tenant__r.Name",
  "Lease__r.Is_Deal_Confidential__c",
  "Lease__r.ascendix__Property__c",
  "Lease__r.ascendix__Property__r.ascendix__Street__c",
  "Lease__r.ascendix__Property__r.ascendix__City__c",
  "Lease__r.ascendix__Property__r.State__c",
  "Lease__r.ascendix__Property__r.Zip_Code__c",
  "Lease__r.ascendix__Property__r.ascendix__PrimaryImage__c",
  "Lease__r.ascendix__Property__r.ascendix__PropertySubType__c",
  "Lease__r.Deal_Type__c",
  "Lease__r.Deal_Sub_Type__c",
  "Lease__r.Lee_Deal__c",
  "Sale__r.ascendix__Buyer__c",
  "Sale__r.ascendix__Buyer__r.Name",
  "Sale__r.ascendix__Buyer__r.Normalized_Name__c",
  "Sale__r.ascendix__Property__c",
  "Sale__r.ascendix__Property__r.ascendix__Street__c",
  "Sale__r.ascendix__Property__r.ascendix__City__c",
  "Sale__r.ascendix__Property__r.State__c",
  "Sale__r.ascendix__Property__r.Zip_Code__c",
  "Sale__r.ascendix__Property__r.ascendix__PrimaryImage__c",
  "Sale__r.ascendix__Property__r.ascendix__PropertySubType__c",
  "Sale__r.Sale_Type__c",
  "Sale__r.Lee_Deal__c",
  "Sale__r.Is_Lee_Deal__c",
  "Sale__r.ascendix__ListingBrokerCompany__c",
  "Sale__r.Procuring_Broker_1_Company__c",
  "Availability__r.ascendix__Property__c",
  "Availability__r.ascendix__Property__r.ascendix__Street__c",
  "Availability__r.ascendix__Property__r.ascendix__City__c",
  "Availability__r.ascendix__Property__r.State__c",
  "Availability__r.ascendix__Property__r.Zip_Code__c",
  "Availability__r.ascendix__Property__r.ascendix__PrimaryImage__c",
  "Availability__r.ascendix__UseSubType__c",
  "Availability__r.Vacancy_Type__c",
  "Availability__r.Listing_Broker_Company__c",
] as const;

export const unverifiedSalesforceMappings = () => [];
