import { rm } from "node:fs/promises";
import { resolveVisualDataDir } from "./visualDataDir";

/**
 * Playwright global teardown. Removes the auto-generated per-run temp data
 * root (see visualDataDir.ts) so disposable Playwright fixtures never
 * accumulate on disk. An explicit `PLAYWRIGHT_DATA_DIR` override is left in
 * place — a developer who names a directory is choosing to inspect it.
 */
export default async function globalTeardown(): Promise<void> {
  const { dir, autoGenerated } = resolveVisualDataDir();
  if (!autoGenerated) return;
  await rm(dir, { recursive: true, force: true });
}
