import { tmpdir } from "node:os";
import path from "node:path";

/**
 * Isolated storage root for the Playwright-driven API server. Defaults to a
 * unique, disposable directory under the OS temp folder per test run
 * (`%TEMP%/lee-report-studio-tests/<run-id>/` on Windows, the POSIX
 * equivalent elsewhere) so automated runs never touch `server/data`, the
 * real development/production template and report-instance store.
 *
 * A developer can still pin `PLAYWRIGHT_DATA_DIR` to a stable, inspectable
 * path across repeated manual runs; an explicit override is never
 * auto-deleted by teardown (see globalTeardown below). This resolution
 * happens once per process (`playwright.config.ts` calls it first) and is
 * memoized through `process.env` so `globalSetup`/`globalTeardown` — which
 * Playwright runs in the same process as config evaluation — see the exact
 * same directory rather than recomputing a fresh timestamp.
 */
export function resolveVisualDataDir(): { dir: string; autoGenerated: boolean } {
  const existing = process.env.PLAYWRIGHT_DATA_DIR;
  if (existing)
    return {
      dir: existing,
      autoGenerated: process.env.PLAYWRIGHT_DATA_DIR_AUTO === "1",
    };
  const runId = `run-${process.pid}-${Date.now()}`;
  const dir = path.join(tmpdir(), "lee-report-studio-tests", runId);
  process.env.PLAYWRIGHT_DATA_DIR = dir;
  process.env.PLAYWRIGHT_DATA_DIR_AUTO = "1";
  return { dir, autoGenerated: true };
}
